- name: create directories in /opt
  tags: ctf, filesystem, opt
  become: yes
  file:
    path: "/opt/{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - tools
    - wordlists

- name: clone GitHub repos
  tags: ctf, github, wordlists, opt
  become: yes
  git:
    repo: "{{ item.repo }}"
    dest: "/opt/{{ item.dir_name }}"
    update: no
  loop:
    - {dir_name: "wordlists/SecLists", repo: "https://github.com/danielmiessler/SecLists.git"}
  loop_control:
    label: "{{ item.dir_name }}"

- name: unpack rockyou.txt
  tags: wordlists
  become: yes
  unarchive:
    src: /opt/wordlists/SecLists/Passwords/Leaked-Databases/rockyou.txt.tar.gz
    dest: /opt/wordlists/SecLists/Passwords/Leaked-Databases
      
- name: download packages from GitHub manually
  tags: ctf, packages, manualdownloads, opt
  become: yes
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.path }}"
  loop: 
    - {path: "/tmp/chisel_amd64.gz", url: "https://github.com/jpillora/chisel/releases/download/v1.7.7/chisel_1.7.7_linux_amd64.gz"}
    - {path: "/tmp/chisel_win_amd64.gz", url: "https://github.com/jpillora/chisel/releases/download/v1.7.7/chisel_1.7.7_windows_amd64.gz"}
    - {path: "/usr/local/bin/kerbrute", url: "https://github.com/ropnop/kerbrute/releases/download/v1.0.3/kerbrute_linux_amd64"}
    - {path: "/tmp/mimikatz_trunk.zip", url: "https://github.com/gentilkiwi/mimikatz/releases/download/2.2.0-20210810-2/mimikatz_trunk.zip"}
    - {path: "/opt/tools/PowerView.ps1", url: "https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/dev/Recon/PowerView.ps1"}
    - {path: "/opt/tools/pspy64", url: "https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64"}
    - {path: "/opt/tools/Rubeus.exe", url: "https://github.com/Flangvik/SharpCollection/raw/master/NetFramework_4.7_x64/Rubeus.exe"}
    - {path: "/opt/tools/Seatbelt.exe", url: "https://github.com/Flangvik/SharpCollection/raw/master/NetFramework_4.7_x64/Seatbelt.exe"}
    - {path: "/opt/tools/SharpHound.exe", url: "https://github.com/BloodHoundAD/BloodHound/raw/master/Collectors/SharpHound.exe"}
    - {path: "/opt/tools/SharpHound.ps1", url: "https://raw.githubusercontent.com/BloodHoundAD/BloodHound/master/Collectors/SharpHound.ps1"}
  loop_control:
    label: "{{ item.url }}"

- name: unpack .gz files
  tags: ctf, packages, manualdownloads, opt
  become: yes
  shell: "gunzip -c {{ item.src }} > {{ item.dest }}"
  args:
    creates: "{{ item.dest }}"
  loop:
    - {src: "/tmp/chisel_amd64.gz", dest: "/opt/tools/chisel"}
    - {src: "/tmp/chisel_win_amd64.gz", dest: "/opt/tools/chisel.exe"}
  loop_control:
    label: "{{ item.dest }}"

- name: unzip mimikatz files
  tags: ctf, packages, manualdownloads, opt
  become: yes
  shell: "unzip -j /tmp/mimikatz_trunk.zip x64/mimikatz.exe -d /opt/tools"
  args:
    creates: "/opt/tools/mimikatz.exe"

