---

- hosts: localhost
  become: true
  pre_tasks:
    
  - name: update cache
    tags: always
    apt:
      update_cache: yes

- hosts: localhost
  roles:
    - kali
    - base
    - users
    - ctf
    - git_repos
    - python
    - go
    - harden_sshd

