---

- hosts: localhost
  become: true
  pre_tasks:
    
  - name: update cache
    tags: always
    apt:
      update_cache: yes

- hosts: localhost
  become: true
  tasks:

  - name: add Kali archive key
    tags: init, kali
    apt_key:
      url: https://archive.kali.org/archive-key.asc
      state: present

  - name: replace all entries in sources.list with Kali
    tags: init, kali
    copy:
      src: sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644

  - name: dist upgrade to Kali
    tags: init, kali
    apt:
      upgrade: dist
      update_cache: yes

  - name: install basic packages
    tags: init, basic
    package:
      name:
        - apt-transport-https
        - curl
        - ftp
        - git
        - grep
        - htop
        - mariadb-client
        - openssh-client
        - tar
        - tmux
        - traceroute
        - unzip
        - vim
        - wget
      state: latest

  - name: install programming languages
    tags: ctf, programming, basic
    apt:
      name:
        - golang
        - python2
        - python3
        - python3-pip
        - python3-venv

  - name: install CTF packages
    tags: ctf, kali
    apt:
      name:
        - dnsutils
        - ffuf
        - gobuster
        - hashcat
        - hydra
        - john
        - metasploit-framework
        - nmap
        - ripgrep
        - silversearcher-ag
        - sqlmap
        - wpscan
      state: latest

- hosts: localhost
  become: true
  
  tasks:

  - name: create directories in /opt
    tags: ctf, filesystem, opt
    file:
      path: "/opt/{{ item }}"
      state: directory
      mode: '0755'
      owner: root
      group: root
    loop:
      - tools
      - wordlists

  - name: clone Github repos
    tags: ctf, github, wordlists, opt
    git:
      repo: "{{ item.repo }}"
      dest: "/opt/{{ item.dir_name }}"
      update: no
    loop:
      - {dir_name: "wordlists/SecLists", repo: "https://github.com/danielmiessler/SecLists.git"}
    loop_control:
      label: "{{ item.dir_name }}"

  - name: unpack rockyou.txt
    tags: wordlists
    unarchive:
      src: /opt/wordlists/SecLists/Passwords/Leaked-Databases/rockyou.txt.tar.gz
      dest: /opt/wordlists/SecLists/Passwords/Leaked-Databases
      
  - name: install Go packages
    tags: ctf, go, packages
    environment:
      GOPATH: "/usr/local/go"
    command: go install "{{ item }}"
    loop:
      - github.com/tomnomnom/anew@latest
    loop_control:
      label: "{{ item }}"

  - name: download packages manually
    tags: ctf, packages, manualdownloads, opt
    get_url:
      url: "{{ item.url }}"
      dest: "/opt/{{ item.path }}"
    loop: 
      - {path: "tools/pspy64", url: "https://github.com/DominicBreuker/pspy/releases/download/v1.2.0/pspy64"}
    loop_control:
      label: "{{ item.url }}"

  - name: download and unpack packages manually
    tags: ctf, packages, manualdownloads, opt
    unarchive:
      src: "{{ item.url }}"
      dest: "/opt/{{ item.path }}"
      remote_src: yes
      mode: 0755
      owner: root
      group: root
    loop:
      - {path: "tools", url: "https://github.com/jpillora/chisel/releases/download/v1.7.7/chisel_1.7.7_linux_amd64.gz"}
      - {path: "tools", url: "https://github.com/jpillora/chisel/releases/download/v1.7.7/chisel_1.7.7_windows_amd64.gz"}
    loop_control:
      label: "{{ item.url }}"
