- name: install Python
  tags: ctf, programming, python
  become: yes
  apt:
    update_cache: yes
    name:
      - python2
      - python3
      - python3-impacket
      - python3-pip
      - python3-venv

