- name: install CTF packages
  tags: ctf, kali
  become: yes
  apt:
    update_cache: yes
    name:
      - crackmapexec
      - dnsutils
      - enum4linux
      - ffuf
      - gobuster
      - hashcat
      - hydra
      - john
      - metasploit-framework
      - nmap
      - ripgrep
      - rlwrap
      - silversearcher-ag
      - smbclient
      - smbmap
      - sqlmap
      - wpscan
    state: latest

