- name: create user account
  tags: users
  become: yes
  user:
    name: '{{ lookup("env", "ANSIBLE_USER") }}'
    uid: 1000
    shell: /bin/bash
    groups: sudo
    password: '{{ lookup("env", "ANSIBLE_USERPASS") | password_hash("sha512") }}'
    update_password: on_create

- name: add public key to authorized_keys
  tags: users, ssh
  become: yes
  authorized_key:
    user: '{{ lookup("env", "ANSIBLE_USER") }}'
    key: '{{ lookup("env", "ANSIBLE_PUBKEY") }}'

