- name: update package cache (Debian)
  tags: init, basic
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: update package cache (RedHat)
  tags: init, basic
  become: yes
  dnf:
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: install basic packages
  tags: init, basic
  become: yes
  package:
    name:
      - apt-transport-https
      - build-essential
      - curl
      - ftp
      - gcc
      - git
      - grep
      - htop
      - jq
      - mariadb-client
      - ncat
      - openssh-client
      - openvpn
      - rsync
      - socat
      - tar
      - tmux
      - traceroute
      - unzip
      - vim
      - wget
      - xsel
    state: latest
